// models/RazorpayData.js
import { PrismaClient } from '@prisma/client';
import Razorpay from 'razorpay';

const prisma = new PrismaClient();

const createPayment = async (customerName, customerEmail, customerContact, price) => {
    console.log("razorpay captured price")
    // Create an instance of Razorpay
    const razorpay = new Razorpay({
        key_id: 'rzp_test_Oxv2YtjPuwWXJL', // Replace with your Razorpay live key
        // key_secret: 'your_key_secret_here' // Add your Razorpay secret key here
    });

    // Create an order
    const orderData = {
        amount: price * 100, // Amount in paise (multiply by 100 to convert to paise)
        currency: 'INR',
        receipt: `receipt_${Math.random() * 10000}`, // Unique receipt ID
        notes: {
            address: 'Customer Address'
        }
    };

    try {
        const order = await razorpay.orders.create(orderData);
        
        // Payment options including the order ID
        const options = {
            key: razorpay.key_id,
            amount: order.amount,
            currency: order.currency,
            name: 'Transmogrify Global Pvt. Ltd',
            description: 'Payment for Total Revenue',
            image: 'https://cdn.statically.io/img/transmogriffy.com/wp-content/uploads/2022/03/TWLD5456.jpg?w=1280&quality=100&f=auto',
            order_id: order.id, // Use the order ID generated by Razorpay
            handler: (response) => {
                alert('Payment successful. Payment ID: ' + response.razorpay_payment_id);
                // Add logic to handle payment success (e.g., update database, show success message)
            },
            prefill: {
                name: customerName,
                email: customerEmail,
                contact: customerContact
            },
            theme: {
                color: '#F37254'
            }
        };

        // Open Razorpay payment modal
        const rzp = new window.Razorpay(options);
        rzp.open();
    } catch (error) {
        console.error('Error creating payment:', error);
    }
};

export default createPayment;
